swagger: 2.0

info:  title: Argonaut Provider Directory Server
  description: This profile defines the expected capabilities of a server when conforming to the Argonaut Provider Directory Implementation Guide.
  version: 1.0.0
  # contact:
    # end user to fill out
  license:
    name: null

# host: [user to provide]
# basePath: [user to provide]
schemes:
  - https
  # - http this would not normally be allowed (see doco)
consumes:
produces:
